/* AUTO-GENERATED by scripts/generate_recipes_data.py — nicht von Hand editieren */
export const initialRecipes = [
  {
    "id": "gainer-drink",
    "title": "Gainer Drink",
    "category": "Frühstück",
    "rating": 5,
    "prepTimeMin": 3,
    "kcalPortion": 770,
    "proteinPortion": 55,
    "batch": false,
    "portionen": 1,
    "einfrierbar": false,
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    "tags": [
      "protein",
      "quick"
    ],
    "baseIngredientName": "Whey Protein",
    "baseIngredientQty": 50.0,
    "unit": "g",
    "checklist": [
      {
        "name": "Whey Protein",
        "baseQty": 50.0,
        "unit": "g"
      },
      {
        "name": "Haferflocken",
        "baseQty": 70.0,
        "unit": "g"
      },
      {
        "name": "Milch",
        "baseQty": 300.0,
        "unit": "ml"
      },
      {
        "name": "Banane",
        "baseQty": 1.0,
        "unit": "x"
      },
      {
        "name": "Leinöl (oder Olivenöl)",
        "baseQty": 1.0,
        "unit": "EL"
      },
      {
        "name": "*Grob:** ~770 kcal · ~55g Protein",
        "baseQty": 1,
        "unit": "x"
      },
      {
        "name": "--",
        "baseQty": 1,
        "unit": "x"
      }
    ],
    "steps": [
      {
        "header": "Alles in Mixer",
        "body": "Alles in Mixer",
        "parallel": null,
        "timer": null
      },
      {
        "header": "30 Sekunden mixen",
        "body": "30 Sekunden mixen",
        "parallel": null,
        "timer": 30
      },
      {
        "header": "Sofort trinken (Haferflocken quellen sonst)",
        "body": "Sofort trinken (Haferflocken quellen sonst)\n---",
        "parallel": null,
        "timer": null
      }
    ]
  },
  {
    "id": "fruehstueck-haferflocken-whey",
    "title": "Frühstück — Haferflocken + Whey",
    "category": "Frühstück",
    "rating": 5,
    "prepTimeMin": 3,
    "kcalPortion": 630,
    "proteinPortion": 60,
    "batch": false,
    "portionen": 1,
    "einfrierbar": false,
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    "tags": [
      "protein",
      "quick"
    ],
    "baseIngredientName": "Haferflocken",
    "baseIngredientQty": 80.0,
    "unit": "g",
    "checklist": [
      {
        "name": "Haferflocken",
        "baseQty": 80.0,
        "unit": "g"
      },
      {
        "name": "Whey Protein (Vanille oder Schoko)",
        "baseQty": 50.0,
        "unit": "g"
      },
      {
        "name": "Milch (oder Wasser für weniger Kalorien)",
        "baseQty": 300.0,
        "unit": "ml"
      },
      {
        "name": "Optional: ½ Apfel gewürfelt",
        "baseQty": 1,
        "unit": "x"
      },
      {
        "name": "Optional: 1 EL Leinsamen",
        "baseQty": 1,
        "unit": "x"
      },
      {
        "name": "*Grob:** ~630 kcal · ~60g Protein",
        "baseQty": 1,
        "unit": "x"
      },
      {
        "name": "--",
        "baseQty": 1,
        "unit": "x"
      }
    ],
    "steps": [
      {
        "header": "Haferflocken in Schüssel, Milch dazu.",
        "body": "Haferflocken in Schüssel, Milch dazu.",
        "parallel": null,
        "timer": null
      },
      {
        "header": "2–3 min in Mikrowelle — oder kalt anrühren und 5 min quellen lassen.",
        "body": "2–3 min in Mikrowelle — oder kalt anrühren und 5 min quellen lassen.",
        "parallel": null,
        "timer": 180
      },
      {
        "header": "Whey erst nach dem Erhitzen einrühren (verhindert Klumpen).",
        "body": "Whey erst nach dem Erhitzen einrühren (verhindert Klumpen).",
        "parallel": null,
        "timer": null
      },
      {
        "header": "Apfel und Leinsamen nach Belieben drüber.",
        "body": "Apfel und Leinsamen nach Belieben drüber.\n---",
        "parallel": null,
        "timer": null
      }
    ]
  },
  {
    "id": "muffins-hafer-batch-x-4",
    "title": "Muffins Hafer",
    "category": "Frühstück",
    "rating": 5,
    "prepTimeMin": 85,
    "kcalPortion": 600,
    "proteinPortion": 12,
    "batch": true,
    "portionen": 4,
    "einfrierbar": true,
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    "tags": [
      "prep"
    ],
    "baseIngredientName": "Haferflocken, kernig",
    "baseIngredientQty": 125.0,
    "unit": "g",
    "checklist": [
      {
        "name": "Walnüsse",
        "baseQty": 30.0,
        "unit": "g"
      },
      {
        "name": "Datteln",
        "baseQty": 30.0,
        "unit": "g"
      },
      {
        "name": "Haferflocken, kernig",
        "baseQty": 125.0,
        "unit": "g"
      },
      {
        "name": "Haferflocken, zart",
        "baseQty": 125.0,
        "unit": "g"
      },
      {
        "name": "Backpulver",
        "baseQty": 2.0,
        "unit": "TL"
      },
      {
        "name": "Zimt",
        "baseQty": 1.0,
        "unit": "TL"
      },
      {
        "name": "Leinsamen, geschrotet",
        "baseQty": 1.0,
        "unit": "EL"
      },
      {
        "name": "Hafermilch",
        "baseQty": 250.0,
        "unit": "ml"
      },
      {
        "name": "Sonnenblumenöl",
        "baseQty": 80.0,
        "unit": "ml"
      },
      {
        "name": "reife Bananen",
        "baseQty": 2.0,
        "unit": "x"
      },
      {
        "name": "Mandelmus, ungesüßt (statt Erdnussbutter)",
        "baseQty": 1.0,
        "unit": "EL"
      }
    ],
    "steps": [
      {
        "header": "Vorbereitung (5 Min)",
        "body": "Backofen auf 200°C Ober-/Unterhitze vorheizen. Muffinform für 12 Muffins einfetten oder mit Papierförmchen auslegen. Walnüsse grob hacken, Datteln klein würfeln (wenn sehr trocken: kurz in warmem Wasser einweichen, dann abtropfen lassen).",
        "parallel": null,
        "timer": 300
      },
      {
        "header": "Trockene Zutaten (3 Min)",
        "body": "Beide Haferflocken-Sorten, Backpulver, Zimt und geschroteten Leinsamen in einer großen Schüssel vermengen. Gehackte Walnüsse und Dattelwürfel untermischen.",
        "parallel": null,
        "timer": 180
      },
      {
        "header": "Feuchte Zutaten pürieren (3 Min)",
        "body": "Hafermilch, Sonnenblumenöl und die geschälten Bananen in ein hohes Rührgefäß geben und mit dem Pürierstab fein pürieren, bis keine Klümpchen mehr zu sehen sind.",
        "parallel": null,
        "timer": 180
      },
      {
        "header": "Teig vermengen (2 Min)",
        "body": "Die pürierte Flüssigkeit zu den trockenen Zutaten gießen und mit Löffel oder Spatel gründlich verrühren, bis ein gleichmäßiger, eher fester Teig entsteht.",
        "parallel": null,
        "timer": 120
      },
      {
        "header": "Befüllen & backen (30 Min)",
        "body": "Teig gleichmäßig auf die 12 Muffinmulden verteilen (nicht bis zum Rand, der Teig geht beim Backen kaum auf). Im vorgeheizten Ofen ca. 30 Minuten backen, bis eine Stäbchenprobe sauber herauskommt. Danach mindestens 15–20 Min vollständig in der Form auskühlen lassen, bevor die Muffins herausgelöst werden — frisch aus dem Ofen sind sie noch sehr weich und brechen leicht.",
        "parallel": null,
        "timer": 1800
      },
      {
        "header": "Topping (2 Min)",
        "body": "Mandelmus in einer mikrowellenfesten Tasse ca. 1 Minute bei mittlerer Stufe erwärmen, bis es flüssig-cremig ist. Achtung: alle 20 Sekunden umrühren, damit nichts anbrennt oder überkocht. Ausgekühlte Muffins damit beträufeln oder bepinseln.",
        "parallel": null,
        "timer": 120
      },
      {
        "header": "Kühlen (30 Min)",
        "body": "Muffins mit Mandelmus-Topping ca. 30 Minuten kühl stellen, bis das Topping fest geworden ist.",
        "parallel": null,
        "timer": 1800
      },
      {
        "header": "Portionieren & einfrieren",
        "body": "In 4 Portionen zu je 3 Muffins aufteilen, in Gefrierbeuteln oder -dosen einfrieren.",
        "parallel": null,
        "timer": null
      },
      {
        "header": "Auftauen",
        "body": "Über Nacht im Kühlschrank auftauen lassen, oder kurz aufgebacken (5 Min bei 160°C).\n---",
        "parallel": null,
        "timer": 300
      }
    ]
  },
  {
    "id": "tiramisu-overnight-oats-batch-x-4",
    "title": "Tiramisu Overnight Oats",
    "category": "Frühstück",
    "rating": 5,
    "prepTimeMin": 15,
    "kcalPortion": 523,
    "proteinPortion": 17,
    "batch": true,
    "portionen": 4,
    "einfrierbar": true,
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    "tags": [
      "prep",
      "quick"
    ],
    "baseIngredientName": "Haferflocken, zart",
    "baseIngredientQty": 200.0,
    "unit": "g",
    "checklist": [
      {
        "name": "Haferflocken, zart",
        "baseQty": 200.0,
        "unit": "g"
      },
      {
        "name": "Chiasamen",
        "baseQty": 80.0,
        "unit": "g"
      },
      {
        "name": "Backkakao",
        "baseQty": 2.0,
        "unit": "TL"
      },
      {
        "name": "Zucker",
        "baseQty": 40.0,
        "unit": "g"
      },
      {
        "name": "Espresso (kalt)",
        "baseQty": 260.0,
        "unit": "ml"
      },
      {
        "name": "Mandelmilch",
        "baseQty": 300.0,
        "unit": "ml"
      },
      {
        "name": "Vanillepaste",
        "baseQty": 2.0,
        "unit": "TL"
      },
      {
        "name": "Vanillejoghurt (erst beim Servieren, nicht mit einfrieren)",
        "baseQty": 800.0,
        "unit": "g"
      },
      {
        "name": "Backkakao zum Bestäuben (erst beim Servieren)",
        "baseQty": 2.0,
        "unit": "TL"
      }
    ],
    "steps": [
      {
        "header": "Trockene Mischung (2 Min)",
        "body": "Haferflocken, Chiasamen, Backkakao und Zucker in einer großen Schüssel gründlich vermischen.",
        "parallel": null,
        "timer": 120
      },
      {
        "header": "Flüssigkeit ansetzen (2 Min)",
        "body": "Espresso, Vanillepaste und Mandelmilch in einem separaten Gefäß verrühren, bis sich die Vanillepaste gleichmäßig verteilt hat.",
        "parallel": null,
        "timer": 120
      },
      {
        "header": "Zusammenführen (1 Min)",
        "body": "Flüssigkeit zur Hafer-Chia-Mischung geben und gut verrühren. Mit Frischhaltefolie oder Deckel abdecken.",
        "parallel": null,
        "timer": 60
      },
      {
        "header": "Quellen lassen (mind. 8 Std, am besten über Nacht)",
        "body": "Im Kühlschrank quellen lassen, bis die Chiasamen die Flüssigkeit vollständig aufgenommen haben und die Masse puddingartig fest ist.",
        "parallel": "⚡ Parallel möglich: Dosen/Behälter fürs Portionieren bereitstellen",
        "timer": 28800
      },
      {
        "header": "Portionieren (Basis)",
        "body": "Die fertige Hafer-Chia-Basis in 4 gleiche Portionen aufteilen (je ca. 145g).",
        "parallel": null,
        "timer": null
      },
      {
        "header": "Für den sofortigen Verzehr",
        "body": "In einem Glas abwechselnd Hafer-Chia-Basis und Vanillejoghurt schichten (je zur Hälfte der Portion), zum Abschluss mit etwas Backkakao bestäuben.",
        "parallel": null,
        "timer": null
      },
      {
        "header": "Für die restlichen Portionen zum Einfrieren",
        "body": "Nur die Hafer-Chia-Basis (ohne Joghurt, ohne Kakao) einzeln in Gefrierdosen einfrieren.",
        "parallel": null,
        "timer": null
      },
      {
        "header": "Auftauen & servieren",
        "body": "Portion über Nacht im Kühlschrank auftauen lassen, dann mit frischem Vanillejoghurt schichten und mit Backkakao bestäuben wie in Schritt 6.\n---",
        "parallel": null,
        "timer": null
      }
    ]
  },
  {
    "id": "chili-con-carne-batch-x-3",
    "title": "Chili con Carne",
    "category": "Hauptmahlzeit",
    "rating": 5,
    "prepTimeMin": 50,
    "kcalPortion": 900,
    "proteinPortion": 55,
    "batch": true,
    "portionen": 3,
    "einfrierbar": true,
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    "tags": [
      "protein",
      "prep"
    ],
    "baseIngredientName": "Rinderfaschiertes",
    "baseIngredientQty": 900.0,
    "unit": "g",
    "checklist": [
      {
        "name": "Rinderfaschiertes",
        "baseQty": 900.0,
        "unit": "g"
      },
      {
        "name": "roße Zwiebel",
        "baseQty": 1.0,
        "unit": "g"
      },
      {
        "name": "Knoblauchzehen",
        "baseQty": 3.0,
        "unit": "x"
      },
      {
        "name": "Olivenöl",
        "baseQty": 2.0,
        "unit": "EL"
      },
      {
        "name": "Tomatenmark",
        "baseQty": 1.0,
        "unit": "EL"
      },
      {
        "name": "gehackte Tomaten (2 Dosen)",
        "baseQty": 800.0,
        "unit": "g"
      },
      {
        "name": "Kidneybohnen, abgespült (1 Dose)",
        "baseQty": 400.0,
        "unit": "g"
      },
      {
        "name": "Mais",
        "baseQty": 1.0,
        "unit": "Dose"
      },
      {
        "name": "Paprikapulver edelsüß",
        "baseQty": 2.0,
        "unit": "EL"
      },
      {
        "name": "Kreuzkümmel gemahlen",
        "baseQty": 1.0,
        "unit": "TL"
      },
      {
        "name": "Chilipulver",
        "baseQty": 1.0,
        "unit": "TL"
      },
      {
        "name": "Salz, ½ TL Pfeffer",
        "baseQty": 1.0,
        "unit": "TL"
      },
      {
        "name": "Zartbitterschokolade (optional)",
        "baseQty": 10.0,
        "unit": "g"
      },
      {
        "name": "Olivenöl zum Servieren (kcal-Booster)",
        "baseQty": 1.0,
        "unit": "EL"
      },
      {
        "name": "*Grob:** ~900 kcal · ~55g Protein pro Portion",
        "baseQty": 1,
        "unit": "x"
      },
      {
        "name": "--",
        "baseQty": 1,
        "unit": "x"
      }
    ],
    "steps": [
      {
        "header": "Vorbereitung",
        "body": "Zwiebel fein hacken, Knoblauch pressen. Kidneybohnen abspülen.",
        "parallel": null,
        "timer": null
      },
      {
        "header": "Anschwitzen (5 Min)",
        "body": "Olivenöl in großem Topf (min. 3 L) erhitzen. Zwiebel glasig dünsten, dann Knoblauch kurz dazu.",
        "parallel": null,
        "timer": 300
      },
      {
        "header": "Fleisch anbraten (8 Min)",
        "body": "Hitze hoch, Faschiertes rein, mit Holzlöffel zerteilen, bis Flüssigkeit verdampft und Fleisch leicht bräunt.",
        "parallel": null,
        "timer": 480
      },
      {
        "header": "Tomatenmark rösten (1 Min)",
        "body": "Tomatenmark dazu, kurz mitrösten — macht den Geschmack tief.",
        "parallel": null,
        "timer": 60
      },
      {
        "header": "Gewürze (30 Sek)",
        "body": "Paprikapulver, Kreuzkümmel, Chili, Salz, Pfeffer einarbeiten. Achtung: Paprikapulver verbrennt schnell!",
        "parallel": null,
        "timer": null
      },
      {
        "header": "Tomaten & Bohnen dazu",
        "body": "Gehackte Tomaten, Kidneybohnen, Mais rein. Falls du Schokolade hast: dazu.",
        "parallel": null,
        "timer": null
      },
      {
        "header": "Köcheln (30–45 Min)",
        "body": "Zugedeckt bei niedriger Hitze. Alle 10 Min umrühren.",
        "parallel": "⚡ Parallel möglich: Dosen/Behälter fürs Portionieren bereitstellen",
        "timer": 2700
      },
      {
        "header": "Abschmecken & portionieren",
        "body": "In 3 Portionen aufteilen. Eine für heute, zwei einfrieren. Beim Servieren 1 EL Olivenöl drüber.",
        "parallel": null,
        "timer": null
      }
    ]
  },
  {
    "id": "chinesische-haehnchenpfanne-batch-x-4",
    "title": "Chinesische Hähnchenpfanne",
    "category": "Hauptmahlzeit",
    "rating": 4,
    "prepTimeMin": 40,
    "kcalPortion": 314,
    "proteinPortion": 38,
    "batch": true,
    "portionen": 4,
    "einfrierbar": true,
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    "tags": [
      "protein",
      "prep"
    ],
    "baseIngredientName": "Hähnchenbrustfilets",
    "baseIngredientQty": 500.0,
    "unit": "g",
    "checklist": [
      {
        "name": "Hähnchenbrustfilets",
        "baseQty": 500.0,
        "unit": "g"
      },
      {
        "name": "rote Zwiebeln",
        "baseQty": 2.0,
        "unit": "x"
      },
      {
        "name": "Paprika (bunt gemischt, z.B. rot + gelb), in Streifen",
        "baseQty": 2.0,
        "unit": "x"
      },
      {
        "name": "TK-Erbsen",
        "baseQty": 200.0,
        "unit": "g"
      },
      {
        "name": "Sesamöl (statt Erdnussöl)",
        "baseQty": 4.0,
        "unit": "EL"
      },
      {
        "name": "Sojasauce",
        "baseQty": 100.0,
        "unit": "ml"
      },
      {
        "name": "Chilisoße",
        "baseQty": 6.0,
        "unit": "EL"
      },
      {
        "name": "Salz & Pfeffer",
        "baseQty": 1,
        "unit": "x"
      },
      {
        "name": "Sprossen zum Servieren (frisch, nicht mit einfrieren)",
        "baseQty": 1,
        "unit": "x"
      }
    ],
    "steps": [
      {
        "header": "Fleisch vorbereiten (10 Min)",
        "body": "Hähnchenbrustfilets trockentupfen, von Sehnen und Fett befreien, in feine Streifen schneiden (ca. 0,5 cm breit, damit sie im Wok schnell und gleichmäßig garen).",
        "parallel": null,
        "timer": 600
      },
      {
        "header": "Marinieren (10 Min Ruhezeit)",
        "body": "Fleischstreifen in einer Schüssel mit Salz, Pfeffer und der Hälfte des Sesamöls (2 EL) vermengen, zugedeckt 10 Minuten ziehen lassen.",
        "parallel": "⚡ Parallel: Gemüse vorbereiten (8 Min) — In der Zwischenzeit rote Zwiebeln schälen und in Streifen schneiden, Paprika waschen, entkernen und ebenfalls in Streifen schneiden. TK-Erbsen 2 Minuten in koch…",
        "timer": 600
      },
      {
        "header": "Gemüse vorbereiten (8 Min)",
        "body": "In der Zwischenzeit rote Zwiebeln schälen und in Streifen schneiden, Paprika waschen, entkernen und ebenfalls in Streifen schneiden. TK-Erbsen 2 Minuten in kochendem Salzwasser blanchieren, abgießen und beiseitestellen.",
        "parallel": "In der Zwischenzeit rote Zwiebeln schälen und in Streifen schneiden, Paprika waschen, entkernen und ebenfalls in Streifen schneiden.",
        "timer": 480
      },
      {
        "header": "Gemüse anbraten (2–3 Min pro Durchgang)",
        "body": "Restliches Sesamöl (2 EL) in einem großen Wok oder einer großen Pfanne stark erhitzen, bis es beim Hineinhalten eines Holzlöffels leicht brodelt. Gesamtes Gemüse in 2 Durchgängen (wegen der doppelten Menge — auf einmal würde es dünsten statt braten) je 2–3 Minuten scharf anbraten, bis es leicht Farbe annimmt, aber noch Biss hat. Herausnehmen und beiseitestellen.",
        "parallel": null,
        "timer": 120
      },
      {
        "header": "Fleisch anbraten (3–4 Min pro Durchgang)",
        "body": "Marinierte Hähnchenstreifen ebenfalls portionsweise in den Wok geben (nicht alles auf einmal, sonst kocht das Fleisch im eigenen Saft statt zu braten) und bei hoher Hitze 3–4 Minuten rundum anbraten, bis es außen leicht gebräunt und innen durchgegart ist.",
        "parallel": null,
        "timer": 180
      },
      {
        "header": "Zusammenführen (5 Min)",
        "body": "Hitze auf mittlere Stufe reduzieren. Gemüse zurück in den Wok geben, mit Salz würzen. Sojasauce und Chilisoße dazugeben, alles gut vermengen und 5 Minuten offen einköcheln lassen, bis die Sauce leicht eindickt und alles gleichmäßig überzogen ist.",
        "parallel": null,
        "timer": 300
      },
      {
        "header": "Abschmecken & portionieren",
        "body": "Abschmecken, bei Bedarf nachwürzen. In 4 Portionen aufteilen, auskühlen lassen, dann einfrieren. Sprossen NICHT mit einfrieren — die kommen erst frisch beim Servieren als Topping dazu.",
        "parallel": null,
        "timer": null
      },
      {
        "header": "Auftauen",
        "body": "Über Nacht im Kühlschrank auftauen, in der Pfanne bei mittlerer Hitze durchwärmen, dann mit frischen Sprossen und z.B. Reis servieren.\n---",
        "parallel": null,
        "timer": null
      }
    ]
  },
  {
    "id": "faschiertes-pfanne-batch-x-4",
    "title": "Faschiertes-Pfanne",
    "category": "Hauptmahlzeit",
    "rating": 5,
    "prepTimeMin": 25,
    "kcalPortion": 400,
    "proteinPortion": 30,
    "batch": true,
    "portionen": 4,
    "einfrierbar": true,
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    "tags": [
      "protein",
      "prep",
      "quick"
    ],
    "baseIngredientName": "Faschiertes",
    "baseIngredientQty": 500.0,
    "unit": "g",
    "checklist": [
      {
        "name": "Faschiertes",
        "baseQty": 500.0,
        "unit": "g"
      },
      {
        "name": "Tiefkühlgemüse (~300g)",
        "baseQty": 1.0,
        "unit": "Packung"
      },
      {
        "name": "Zwiebel (gewürfelt)",
        "baseQty": 1.0,
        "unit": "x"
      },
      {
        "name": "Olivenöl",
        "baseQty": 2.0,
        "unit": "EL"
      },
      {
        "name": "Paprika geräuchert",
        "baseQty": 1.0,
        "unit": "TL"
      },
      {
        "name": "Kreuzkümmel",
        "baseQty": 1.0,
        "unit": "TL"
      },
      {
        "name": "Knoblauchpulver",
        "baseQty": 0.5,
        "unit": "TL"
      },
      {
        "name": "Salz",
        "baseQty": 1.0,
        "unit": "TL"
      },
      {
        "name": "Pfeffer",
        "baseQty": 0.5,
        "unit": "TL"
      },
      {
        "name": "Spritzer Worcestersauce (optional)",
        "baseQty": 1,
        "unit": "x"
      },
      {
        "name": "Optional Beilage: 4 × 100g Nudeln (roh) → separat kochen (8–10 min)",
        "baseQty": 1,
        "unit": "x"
      }
    ],
    "steps": [
      {
        "header": "Zwiebel in Öl anschwitzen (3 min)",
        "body": "Zwiebel in Öl anschwitzen (3 min)",
        "parallel": null,
        "timer": 180
      },
      {
        "header": "Faschiertes dazu, krümelig braten (5–7 min)",
        "body": "Faschiertes dazu, krümelig braten (5–7 min)",
        "parallel": null,
        "timer": 300
      },
      {
        "header": "Gewürze dazu, umrühren",
        "body": "Gewürze dazu, umrühren",
        "parallel": null,
        "timer": null
      },
      {
        "header": "Tiefkühlgemüse dazu, Deckel drauf, 10 min",
        "body": "Tiefkühlgemüse dazu, Deckel drauf, 10 min",
        "parallel": "⚡ Parallel: Optional Beilage: 4 × 100g Nudeln (roh) → separat kochen (8–10 min)",
        "timer": 600
      },
      {
        "header": "Abschmecken, fertig",
        "body": "Abschmecken, fertig\n---",
        "parallel": null,
        "timer": null
      }
    ]
  },
  {
    "id": "haehnchen-suess-sauer-batch-x-4",
    "title": "Hähnchen süß-sauer",
    "category": "Hauptmahlzeit",
    "rating": 5,
    "prepTimeMin": 30,
    "kcalPortion": 340,
    "proteinPortion": 31,
    "batch": true,
    "portionen": 4,
    "einfrierbar": true,
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    "tags": [
      "protein",
      "prep",
      "quick"
    ],
    "baseIngredientName": "Hähnchenbrustfilet",
    "baseIngredientQty": 500.0,
    "unit": "g",
    "checklist": [
      {
        "name": "Hähnchenbrustfilet",
        "baseQty": 500.0,
        "unit": "g"
      },
      {
        "name": "Sojasauce + 2 EL kaltes Wasser (Ersatz für Ei zum Befeuchten)",
        "baseQty": 2.0,
        "unit": "EL"
      },
      {
        "name": "Speisestärke (zum Bestäuben des Fleischs)",
        "baseQty": 2.0,
        "unit": "EL"
      },
      {
        "name": "rote Paprika",
        "baseQty": 1.0,
        "unit": "x"
      },
      {
        "name": "Karotte",
        "baseQty": 1.0,
        "unit": "x"
      },
      {
        "name": "Ananas in Stücken (ungezuckert, ca. 360g Abtropfgewicht + Ananassaft auffangen)",
        "baseQty": 1.0,
        "unit": "Dose"
      },
      {
        "name": "Essig (Apfelessig oder Reisessig)",
        "baseQty": 6.0,
        "unit": "EL"
      },
      {
        "name": "Zucker (oder brauner Zucker / Erythrit)",
        "baseQty": 2.0,
        "unit": "EL"
      },
      {
        "name": "Tomatenmark",
        "baseQty": 2.0,
        "unit": "EL"
      },
      {
        "name": "Sojasauce (für die Sauce)",
        "baseQty": 2.0,
        "unit": "EL"
      },
      {
        "name": "Sesamöl",
        "baseQty": 1.0,
        "unit": "EL"
      },
      {
        "name": "Salz & Pfeffer",
        "baseQty": 1.0,
        "unit": "TL"
      },
      {
        "name": "Speisestärke (zum Binden der Sauce)",
        "baseQty": 2.0,
        "unit": "EL"
      },
      {
        "name": "Beilage: 4 × 60g Reis (roh) → separat kochen",
        "baseQty": 1,
        "unit": "x"
      }
    ],
    "steps": [
      {
        "header": "Fleisch vorbereiten & marinieren (5 Min)",
        "body": "Hähnchenbrustfilet in mundgerechte Würfel schneiden. Mit Salz, Pfeffer und 2 EL Sojasauce + 2 EL Wasser vermengen (macht das Fleisch saftig und lässt die Stärke haften – **ohne Ei**). Anschließend mit 2 EL Speisestärke bestäuben und gut durchmischen, sodass alle Stücke gleichmäßig umhüllt sind.",
        "parallel": "⚡ Parallel: Beilage: 4 × 60g Reis (roh) → separat kochen",
        "timer": 300
      },
      {
        "header": "Fleisch anbraten (7 Min)",
        "body": "In einer großen Pfanne oder einem Wok 1–2 EL Pflanzenöl erhitzen. Hähnchenwürfel bei hoher Hitze ca. 5–7 Minuten goldbraun und knusprig anbraten. Herausnehmen und auf einem Teller beiseitestellen.",
        "parallel": null,
        "timer": 420
      },
      {
        "header": "Gemüse & Ananas vorbereiten (5 Min)",
        "body": "Paprika entkernen und in mundgerechte Stücke schneiden. Karotte schälen und in dünne Scheiben schneiden. Ananas abgießen, dabei den **Ananassaft vollständig in einer Schüssel auffangen**.",
        "parallel": null,
        "timer": 300
      },
      {
        "header": "Süß-Saure Sauce anrühren (3 Min)",
        "body": "In einer kleinen Schale 2 EL Speisestärke mit 3–4 EL des aufgefangenen Ananassafts klümpchenfrei glattrühren. In einem kleinen Topf den restlichen Ananassaft, Essig, Zucker, Tomatenmark, Sojasauce, Sesamöl und 1 TL Salz verrühren und aufkochen. Die angerührte Stärke einrühren und unter ständigem Rühren 1 Minute leicht köcheln lassen, bis die Sauce andickt.",
        "parallel": null,
        "timer": 180
      },
      {
        "header": "Gemüse garen & vereinen (5 Min)",
        "body": "Paprika, Karottenscheiben und Ananasstücke zur eingedickten Sauce geben und 5–8 Minuten bei mittlerer Hitze knackig-gar köcheln lassen. Zum Schluss das gebratene Hähnchen unterheben und kurz erhitzen.",
        "parallel": null,
        "timer": 300
      },
      {
        "header": "Servieren",
        "body": "Zu frisch gekochtem Reis anrichten.\n---",
        "parallel": null,
        "timer": null
      }
    ]
  },
  {
    "id": "huehnerfrikassee-batch-x-4",
    "title": "Hühnerfrikassee",
    "category": "Hauptmahlzeit",
    "rating": 5,
    "prepTimeMin": 35,
    "kcalPortion": 436,
    "proteinPortion": 44,
    "batch": true,
    "portionen": 4,
    "einfrierbar": true,
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    "tags": [
      "protein",
      "prep"
    ],
    "baseIngredientName": "Hähnchenbrustfilet",
    "baseIngredientQty": 500.0,
    "unit": "g",
    "checklist": [
      {
        "name": "Hähnchenbrustfilet",
        "baseQty": 500.0,
        "unit": "g"
      },
      {
        "name": "Zwiebeln",
        "baseQty": 2.0,
        "unit": "x"
      },
      {
        "name": "Karotten",
        "baseQty": 4.0,
        "unit": "x"
      },
      {
        "name": "Champignons",
        "baseQty": 200.0,
        "unit": "g"
      },
      {
        "name": "Butter",
        "baseQty": 40.0,
        "unit": "g"
      },
      {
        "name": "Mehl",
        "baseQty": 2.0,
        "unit": "EL"
      },
      {
        "name": "Hühnerbrühe",
        "baseQty": 400.0,
        "unit": "ml"
      },
      {
        "name": "Senf",
        "baseQty": 2.0,
        "unit": "TL"
      },
      {
        "name": "Erbsen (TK oder aus der Dose)",
        "baseQty": 200.0,
        "unit": "g"
      },
      {
        "name": "Kochsahne (15% Fett)",
        "baseQty": 100.0,
        "unit": "ml"
      },
      {
        "name": "Salz & Pfeffer",
        "baseQty": 1,
        "unit": "x"
      },
      {
        "name": "Beilage: 4 × 60g Reis (roh) → separat kochen",
        "baseQty": 1,
        "unit": "x"
      }
    ],
    "steps": [
      {
        "header": "Hähnchen kochen (10 Min)",
        "body": "Hähnchenbrustfilets in einem Topf mit reichlich Salzwasser bedecken, aufkochen und 10 Minuten köcheln lassen, bis das Fleisch durchgegart ist. Herausnehmen, kurz abkühlen lassen, dann in mundgerechte Würfel schneiden oder mit zwei Gabeln zerrupfen. Kochwasser wegschütten.",
        "parallel": "⚡ Parallel: Beilage: 4 × 60g Reis (roh) → separat kochen",
        "timer": 600
      },
      {
        "header": "Gemüse vorbereiten (8 Min)",
        "body": "Zwiebeln schälen und fein würfeln. Karotten schälen und in dünne Scheiben schneiden. Champignons trocken mit Küchenpapier abreiben (nicht waschen, sonst ziehen sie Wasser) und ebenfalls in Scheiben schneiden.",
        "parallel": null,
        "timer": 480
      },
      {
        "header": "Anschwitzen (3 Min)",
        "body": "Butter in einem großen Topf (mind. 4 L, wegen der Batch-Menge) bei mittlerer Hitze auslassen. Zwiebeln darin glasig dünsten, nicht bräunen lassen.",
        "parallel": null,
        "timer": 180
      },
      {
        "header": "Gemüse anbraten (2 Min)",
        "body": "Champignons und Karottenscheiben dazugeben, kurz mitbraten, bis die Champignons Farbe annehmen und etwas Flüssigkeit ziehen.",
        "parallel": null,
        "timer": 120
      },
      {
        "header": "Mehlschwitze (1 Min)",
        "body": "Mehl über das Gemüse stäuben, gut verrühren, damit sich das Mehl mit dem Fett verbindet, und kurz mit anschwitzen — sonst schmeckt die Sauce später mehlig. Achtung: bei zu hoher Hitze brennt das Mehl schnell an, Hitze notfalls reduzieren.",
        "parallel": null,
        "timer": 60
      },
      {
        "header": "Ablöschen & köcheln (5 Min)",
        "body": "Mit der Hühnerbrühe unter ständigem Rühren ablöschen, damit keine Klumpen entstehen. Senf und Erbsen einrühren, bei mittlerer Hitze 5 Minuten offen köcheln lassen, bis die Sauce sichtbar andickt.",
        "parallel": null,
        "timer": 300
      },
      {
        "header": "Fertigstellen (2 Min)",
        "body": "Hähnchenwürfel und Kochsahne einrühren, nur kurz erhitzen — nicht mehr aufkochen, sonst kann die Sahne ausflocken. Mit Salz und Pfeffer abschmecken.",
        "parallel": null,
        "timer": 120
      },
      {
        "header": "Portionieren & einfrieren",
        "body": "In 4 Portionsdosen aufteilen (je ca. 350–400g), vollständig auskühlen lassen, bevor die Dosen verschlossen und eingefroren werden. Reis separat kochen und nicht mitfrieren, sondern frisch dazu servieren.",
        "parallel": null,
        "timer": null
      },
      {
        "header": "Auftauen",
        "body": "Über Nacht im Kühlschrank auftauen, dann bei niedriger Hitze im Topf langsam erwärmen und dabei gelegentlich umrühren — Cremesaucen können beim schnellen Erhitzen leicht anbrennen.\n---",
        "parallel": null,
        "timer": null
      }
    ]
  },
  {
    "id": "kichererbsen-pfanne-batch-x-3",
    "title": "Kichererbsen-Pfanne",
    "category": "Hauptmahlzeit",
    "rating": 5,
    "prepTimeMin": 15,
    "kcalPortion": 350,
    "proteinPortion": 14,
    "batch": true,
    "portionen": 3,
    "einfrierbar": false,
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    "tags": [
      "prep",
      "quick"
    ],
    "baseIngredientName": "n Kichererbsen",
    "baseIngredientQty": 2.0,
    "unit": "Dose",
    "checklist": [
      {
        "name": "n Kichererbsen (abgespült)",
        "baseQty": 2.0,
        "unit": "Dose"
      },
      {
        "name": "Tiefkühlgemüse (~300g)",
        "baseQty": 1.0,
        "unit": "Packung"
      },
      {
        "name": "Olivenöl",
        "baseQty": 2.0,
        "unit": "EL"
      },
      {
        "name": "Za'atar",
        "baseQty": 1.0,
        "unit": "TL"
      },
      {
        "name": "Paprika geräuchert",
        "baseQty": 1.0,
        "unit": "TL"
      },
      {
        "name": "Knoblauchpulver",
        "baseQty": 0.5,
        "unit": "TL"
      },
      {
        "name": "Salz",
        "baseQty": 1.0,
        "unit": "TL"
      },
      {
        "name": "Spritzer Zitrone",
        "baseQty": 1,
        "unit": "x"
      }
    ],
    "steps": [
      {
        "header": "Öl in Pfanne erhitzen",
        "body": "Öl in Pfanne erhitzen",
        "parallel": null,
        "timer": null
      },
      {
        "header": "Kichererbsen rein, 3–4 min anrösten bis leicht knusprig",
        "body": "Kichererbsen rein, 3–4 min anrösten bis leicht knusprig",
        "parallel": null,
        "timer": 240
      },
      {
        "header": "Tiefkühlgemüse dazu, Deckel drauf, 7 min",
        "body": "Tiefkühlgemüse dazu, Deckel drauf, 7 min",
        "parallel": null,
        "timer": 420
      },
      {
        "header": "Gewürze + Zitrone drüber, fertig",
        "body": "Gewürze + Zitrone drüber, fertig\n---",
        "parallel": null,
        "timer": null
      }
    ]
  },
  {
    "id": "linsen-bolognese-batch-x-3",
    "title": "Linsen-Bolognese",
    "category": "Hauptmahlzeit",
    "rating": 5,
    "prepTimeMin": 45,
    "kcalPortion": 850,
    "proteinPortion": 55,
    "batch": true,
    "portionen": 3,
    "einfrierbar": true,
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    "tags": [
      "protein",
      "prep"
    ],
    "baseIngredientName": "Rinderfaschiertes",
    "baseIngredientQty": 600.0,
    "unit": "g",
    "checklist": [
      {
        "name": "Rinderfaschiertes",
        "baseQty": 600.0,
        "unit": "g"
      },
      {
        "name": "rote Linsen (trocken)",
        "baseQty": 300.0,
        "unit": "g"
      },
      {
        "name": "passierte Tomaten",
        "baseQty": 1.2,
        "unit": "L"
      },
      {
        "name": "mittlere Zwiebeln",
        "baseQty": 2.0,
        "unit": "x"
      },
      {
        "name": "Knoblauchzehen",
        "baseQty": 3.0,
        "unit": "x"
      },
      {
        "name": "Olivenöl",
        "baseQty": 2.0,
        "unit": "EL"
      },
      {
        "name": "Tomatenmark",
        "baseQty": 1.0,
        "unit": "EL"
      },
      {
        "name": "Wasser oder Brühe",
        "baseQty": 400.0,
        "unit": "ml"
      },
      {
        "name": "Salz, ½ TL Pfeffer",
        "baseQty": 1.0,
        "unit": "TL"
      },
      {
        "name": "Je 1 TL getrockneter Oregano + Basilikum",
        "baseQty": 1,
        "unit": "x"
      },
      {
        "name": "Pasta (frisch kochen, nicht einfrieren!)",
        "baseQty": 500.0,
        "unit": "g"
      },
      {
        "name": "Olivenöl zum Servieren",
        "baseQty": 1.0,
        "unit": "EL"
      },
      {
        "name": "*Grob:** ~850 kcal · ~55g Protein pro Portion (mit 80g Pasta)",
        "baseQty": 1,
        "unit": "x"
      },
      {
        "name": "--",
        "baseQty": 1,
        "unit": "x"
      }
    ],
    "steps": [
      {
        "header": "Vorbereitung",
        "body": "Zwiebeln fein würfeln, Knoblauch pressen. Linsen kalt abspülen.",
        "parallel": null,
        "timer": null
      },
      {
        "header": "Anschwitzen (5 Min)",
        "body": "Olivenöl im großen Topf, Zwiebeln glasig dünsten, Knoblauch kurz dazu.",
        "parallel": null,
        "timer": 300
      },
      {
        "header": "Anbraten (8 Min)",
        "body": "Hitze hoch, Faschiertes rein, scharf anbraten und zerkleinern.",
        "parallel": null,
        "timer": 480
      },
      {
        "header": "Tomatenmark (1 Min)",
        "body": "Dazu, kurz mitrösten.",
        "parallel": null,
        "timer": 60
      },
      {
        "header": "Alles rein",
        "body": "Passierte Tomaten, Linsen, Wasser/Brühe, Gewürze. Gut umrühren.",
        "parallel": null,
        "timer": null
      },
      {
        "header": "Köcheln (25–30 Min)",
        "body": "Niedrige Hitze, zugedeckt. Falls zu dick → etwas Wasser dazu.",
        "parallel": "⚡ Parallel: 500g Pasta (frisch kochen, nicht einfrieren!)",
        "timer": 1800
      },
      {
        "header": "Portionieren",
        "body": "Sauce in 3 Portionen aufteilen. **Wichtig: Pasta IMMER frisch kochen** — gefrorene Pasta wird matschig.",
        "parallel": null,
        "timer": null
      }
    ]
  },
  {
    "id": "linseneintopf-batch-x-4",
    "title": "Linseneintopf",
    "category": "Hauptmahlzeit",
    "rating": 5,
    "prepTimeMin": 30,
    "kcalPortion": 380,
    "proteinPortion": 20,
    "batch": true,
    "portionen": 4,
    "einfrierbar": false,
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    "tags": [
      "prep",
      "quick"
    ],
    "baseIngredientName": "rote Biolinsen",
    "baseIngredientQty": 250.0,
    "unit": "g",
    "checklist": [
      {
        "name": "rote Biolinsen",
        "baseQty": 250.0,
        "unit": "g"
      },
      {
        "name": "geschälte Tomaten",
        "baseQty": 1.0,
        "unit": "Dose"
      },
      {
        "name": "Kichererbsen (abgespült)",
        "baseQty": 1.0,
        "unit": "Dose"
      },
      {
        "name": "Zwiebel (gewürfelt)",
        "baseQty": 1.0,
        "unit": "x"
      },
      {
        "name": "Olivenöl",
        "baseQty": 2.0,
        "unit": "EL"
      },
      {
        "name": "Kreuzkümmel",
        "baseQty": 1.0,
        "unit": "TL"
      },
      {
        "name": "Paprika geräuchert",
        "baseQty": 1.0,
        "unit": "TL"
      },
      {
        "name": "Baharat",
        "baseQty": 1.0,
        "unit": "TL"
      },
      {
        "name": "Salz",
        "baseQty": 1.0,
        "unit": "TL"
      },
      {
        "name": "Pfeffer",
        "baseQty": 0.5,
        "unit": "TL"
      },
      {
        "name": "Wasser",
        "baseQty": 700.0,
        "unit": "ml"
      }
    ],
    "steps": [
      {
        "header": "Zwiebel in Öl anschwitzen (3 min)",
        "body": "Zwiebel in Öl anschwitzen (3 min)",
        "parallel": null,
        "timer": 180
      },
      {
        "header": "Gewürze dazu, kurz rösten (1 min)",
        "body": "Gewürze dazu, kurz rösten (1 min)",
        "parallel": null,
        "timer": 60
      },
      {
        "header": "Linsen, Tomaten, Wasser dazu",
        "body": "Linsen, Tomaten, Wasser dazu",
        "parallel": null,
        "timer": null
      },
      {
        "header": "15 min köcheln bis Linsen weich",
        "body": "15 min köcheln bis Linsen weich",
        "parallel": null,
        "timer": 900
      },
      {
        "header": "Kichererbsen dazu, weitere 5 min",
        "body": "Kichererbsen dazu, weitere 5 min",
        "parallel": null,
        "timer": 300
      },
      {
        "header": "Abschmecken, fertig",
        "body": "Abschmecken, fertig\n---",
        "parallel": null,
        "timer": null
      }
    ]
  },
  {
    "id": "nudelsalat-ohne-mayonnaise",
    "title": "Nudelsalat ohne Mayonnaise",
    "category": "Hauptmahlzeit",
    "rating": 5,
    "prepTimeMin": 25,
    "kcalPortion": 492,
    "proteinPortion": 17,
    "batch": false,
    "portionen": 3,
    "einfrierbar": false,
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    "tags": [
      "quick"
    ],
    "baseIngredientName": "Pasta",
    "baseIngredientQty": 300.0,
    "unit": "g",
    "checklist": [
      {
        "name": "Pasta (z.B. Fusilli oder Farfalle)",
        "baseQty": 300.0,
        "unit": "g"
      },
      {
        "name": "Schalotten",
        "baseQty": 45.0,
        "unit": "g"
      },
      {
        "name": "Paprika",
        "baseQty": 0.75,
        "unit": "x"
      },
      {
        "name": "Apfel",
        "baseQty": 0.75,
        "unit": "x"
      },
      {
        "name": "Gewürzgurken",
        "baseQty": 75.0,
        "unit": "g"
      },
      {
        "name": "Mais (aus der Dose, abgetropft)",
        "baseQty": 115.0,
        "unit": "g"
      },
      {
        "name": "Blattpetersilie",
        "baseQty": 0.75,
        "unit": "Bund"
      },
      {
        "name": "Joghurt",
        "baseQty": 150.0,
        "unit": "g"
      },
      {
        "name": "⅓ Bio-Limette (Saft + Abrieb)",
        "baseQty": 1,
        "unit": "x"
      },
      {
        "name": "Olivenöl",
        "baseQty": 0.75,
        "unit": "EL"
      },
      {
        "name": "Salz, Pfeffer, Zucker",
        "baseQty": 1,
        "unit": "x"
      },
      {
        "name": "*Grob:** ~492 kcal · ~17g Protein pro Portion (Wert von eat.de, nicht geschätzt)",
        "baseQty": 1,
        "unit": "x"
      },
      {
        "name": "--",
        "baseQty": 1,
        "unit": "x"
      }
    ],
    "steps": [
      {
        "header": "Nudeln kochen (10 Min)",
        "body": "Reichlich Salzwasser aufkochen, Nudeln nach Packungsangabe bissfest kochen. Abgießen, kurz kalt abschrecken (verhindert Verkleben und Nachgaren), in eine große Schüssel geben.",
        "parallel": null,
        "timer": 600
      },
      {
        "header": "Gemüse würfeln (8 Min)",
        "body": "Schalotten schälen und sehr fein würfeln. Paprika waschen, entkernen, in kleine Würfel schneiden. Apfel waschen, vierteln, Kerngehäuse entfernen, in kleine Würfel schneiden — am besten gleich mit dem Dressing vermengen, dann läuft er nicht braun an. Gewürzgurken ebenfalls fein würfeln.",
        "parallel": null,
        "timer": 480
      },
      {
        "header": "Zusammenführen (2 Min)",
        "body": "Alle Gemüsewürfel und den abgetropften Mais zu den Nudeln geben. Petersilie waschen, trockenschütteln, fein hacken und untermengen.",
        "parallel": null,
        "timer": 120
      },
      {
        "header": "Dressing (3 Min)",
        "body": "Joghurt in eine kleine Schüssel geben. Limette heiß abwaschen, Schale fein abreiben, halbieren und auspressen. Abrieb und Saft zum Joghurt geben, Olivenöl dazu, mit Salz, Pfeffer und einer Prise Zucker abschmecken — der Zucker rundet die Säure der Limette ab.",
        "parallel": null,
        "timer": 180
      },
      {
        "header": "Vermengen (2 Min)",
        "body": "Dressing über den Salat geben, alles gründlich vermengen, bis alles gleichmäßig überzogen ist.",
        "parallel": null,
        "timer": 120
      },
      {
        "header": "Durchziehen (mind. 30 Min)",
        "body": "Zugedeckt im Kühlschrank mindestens 30 Minuten durchziehen lassen, damit sich die Aromen verbinden. Vor dem Servieren nochmals abschmecken — Nudeln saugen beim Ziehen Salz und Säure auf, meist muss nachgewürzt werden.\n---",
        "parallel": null,
        "timer": 1800
      }
    ]
  },
  {
    "id": "omas-kartoffelsuppe-mit-wuerstchen-batch-x-4",
    "title": "Omas Kartoffelsuppe mit Würstchen",
    "category": "Hauptmahlzeit",
    "rating": 5,
    "prepTimeMin": 35,
    "kcalPortion": 420,
    "proteinPortion": 18,
    "batch": true,
    "portionen": 4,
    "einfrierbar": true,
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    "tags": [
      "prep"
    ],
    "baseIngredientName": "Kartoffeln",
    "baseIngredientQty": 1.0,
    "unit": "kg",
    "checklist": [
      {
        "name": "Kartoffeln (vorwiegend festkochend oder mehlreich)",
        "baseQty": 1.0,
        "unit": "kg"
      },
      {
        "name": "Suppengrün (ca. 500g: Karotten, Sellerie, Lauch, Petersilie)",
        "baseQty": 1.0,
        "unit": "Bund"
      },
      {
        "name": "Zwiebel",
        "baseQty": 1.0,
        "unit": "x"
      },
      {
        "name": "Knoblauchzehe",
        "baseQty": 1.0,
        "unit": "x"
      },
      {
        "name": "Olivenöl (oder Butter)",
        "baseQty": 2.0,
        "unit": "EL"
      },
      {
        "name": "Gemüsebrühe",
        "baseQty": 1.0,
        "unit": "L"
      },
      {
        "name": "Sahne (oder Kochsahne 15%)",
        "baseQty": 100.0,
        "unit": "ml"
      },
      {
        "name": "Würstchen (z. B. Debreziner, Frankfurter oder Wiener)",
        "baseQty": 4.0,
        "unit": "x"
      },
      {
        "name": "Salz, Pfeffer & 1 Prise frisch geriebene Muskatnuss",
        "baseQty": 1,
        "unit": "x"
      }
    ],
    "steps": [
      {
        "header": "Gemüse schnippeln (10 Min)",
        "body": "Kartoffeln schälen und in ca. 2 cm große Würfel schneiden. Suppengrün gründlich waschen: Karotten und Sellerie schälen und würfeln, Lauch in dünne Ringe schneiden. Zwiebel und Knoblauch schälen und fein würfeln.",
        "parallel": null,
        "timer": 600
      },
      {
        "header": "Anschwitzen (5 Min)",
        "body": "Olivenöl in einem großen Suppentopf (mind. 3–4 Liter) bei mittlerer Hitze erwärmen. Zwiebeln und Knoblauch darin 3 Minuten glasig dünsten. Kartoffeln und das vorbereitete Suppengrün dazugeben und 3–5 Minuten unter Rühren mitanbraten (bringt Röstaromen).",
        "parallel": null,
        "timer": 300
      },
      {
        "header": "Ablöschen & Köcheln (15 Min)",
        "body": "Mit der Gemüsebrühe ablöschen, abdecken und bei mittlerer Hitze 15–20 Minuten sanft köcheln lassen, bis die Kartoffeln und das Gemüse butterweich sind.",
        "parallel": "⚡ Parallel möglich: Würstchen schon in Scheiben schneiden",
        "timer": 900
      },
      {
        "header": "Cremig stampfen",
        "body": "Den Topf vom Herd nehmen. Die Suppe nach Wunsch entweder mit dem Pürierstab teilweise anpürieren oder mit einem Kartoffelstampfer grob anstampfen (so entsteht die typisch sämige Konsistenz mit leckeren Gemüsestückchen).",
        "parallel": null,
        "timer": null
      },
      {
        "header": "Fertigstellen (5 Min)",
        "body": "Sahne einrühren. Die Würstchen in dünne Scheiben schneiden, zur Suppe geben und 5 Minuten bei schwacher Hitze gar ziehen lassen (nicht mehr kochend sprudeln lassen, sonst platzen die Würstchen auf). Mit Salz, Pfeffer und Muskatnuss kräftig abschmecken.\n---",
        "parallel": null,
        "timer": 300
      }
    ]
  },
  {
    "id": "one-pot-spinat-lachs-pasta-batch-x-4",
    "title": "One Pot Spinat-Lachs-Pasta",
    "category": "Hauptmahlzeit",
    "rating": 5,
    "prepTimeMin": 40,
    "kcalPortion": 1124,
    "proteinPortion": 54,
    "batch": true,
    "portionen": 4,
    "einfrierbar": true,
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    "tags": [
      "protein",
      "prep"
    ],
    "baseIngredientName": "Lachsfilet",
    "baseIngredientQty": 500.0,
    "unit": "g",
    "checklist": [
      {
        "name": "Lachsfilet",
        "baseQty": 500.0,
        "unit": "g"
      },
      {
        "name": "Olivenöl",
        "baseQty": 2.0,
        "unit": "EL"
      },
      {
        "name": "Bio-Zitronen (Saft + etwas Abrieb)",
        "baseQty": 2.0,
        "unit": "x"
      },
      {
        "name": "Blattspinat",
        "baseQty": 300.0,
        "unit": "g"
      },
      {
        "name": "Zwiebeln",
        "baseQty": 2.0,
        "unit": "x"
      },
      {
        "name": "Knoblauchzehen",
        "baseQty": 2.0,
        "unit": "x"
      },
      {
        "name": "Butterschmalz",
        "baseQty": 2.0,
        "unit": "EL"
      },
      {
        "name": "Weißwein",
        "baseQty": 200.0,
        "unit": "ml"
      },
      {
        "name": "Kochsahne (15% Fett)",
        "baseQty": 400.0,
        "unit": "ml"
      },
      {
        "name": "Gemüsebrühe",
        "baseQty": 900.0,
        "unit": "ml"
      },
      {
        "name": "Orecchiette",
        "baseQty": 500.0,
        "unit": "g"
      },
      {
        "name": "Parmesan (gerieben)",
        "baseQty": 100.0,
        "unit": "g"
      },
      {
        "name": "Salz & Pfeffer",
        "baseQty": 1,
        "unit": "x"
      }
    ],
    "steps": [
      {
        "header": "Lachs vorbereiten (10 Min)",
        "body": "Lachsfilet unter kaltem Wasser abspülen, mit den Fingern nach Gräten abtasten und diese mit einer Pinzette entfernen. Trockentupfen und in ca. 2 cm große Würfel schneiden. In einer Schüssel mit Olivenöl, Zitronensaft, etwas Zitronenabrieb, Salz und Pfeffer vermengen und beiseitestellen zum Marinieren.",
        "parallel": null,
        "timer": 600
      },
      {
        "header": "Gemüse vorbereiten (5 Min)",
        "body": "Spinat gründlich waschen und in einem Sieb abtropfen lassen. Zwiebeln und Knoblauchzehen schälen und fein würfeln.",
        "parallel": null,
        "timer": 300
      },
      {
        "header": "Anbraten (2 Min)",
        "body": "Butterschmalz in einem sehr großen Topf (mind. 5–6 L, wegen der doppelten Menge) bei mittlerer bis hoher Hitze erhitzen. Zwiebel- und Knoblauchwürfel darin ca. 2 Minuten glasig dünsten.",
        "parallel": null,
        "timer": 120
      },
      {
        "header": "Lachs anbraten (2 Min)",
        "body": "Marinierte Lachswürfel dazugeben und weitere 2 Minuten vorsichtig mitbraten und wenden — der Lachs muss hier noch nicht durchgaren, das passiert später beim Köcheln.",
        "parallel": null,
        "timer": 120
      },
      {
        "header": "Ablöschen (1 Min)",
        "body": "Mit Weißwein ablöschen und kurz aufkochen lassen, damit der Alkohol verdampft.",
        "parallel": null,
        "timer": 60
      },
      {
        "header": "Sauce aufbauen (1 Min)",
        "body": "Kochsahne, Gemüsebrühe und Spinat dazugeben, vorsichtig unterrühren — der Spinat fällt schnell in sich zusammen, das ist normal.",
        "parallel": null,
        "timer": 60
      },
      {
        "header": "Nudeln garen (12–15 Min)",
        "body": "Orecchiette einrühren, mit Salz und Pfeffer würzen. Deckel auflegen und bei mittlerer Hitze köcheln lassen, alle paar Minuten umrühren, damit die Nudeln nicht am Boden ansetzen. Bei der doppelten Menge dauert es meist 2–3 Minuten länger als bei der Originalmenge — Nudeln zwischendurch auf Bissfestigkeit prüfen.",
        "parallel": "⚡ Parallel möglich: Dosen/Behälter fürs Portionieren bereitstellen",
        "timer": 900
      },
      {
        "header": "Fertigstellen (2 Min)",
        "body": "Vom Herd nehmen, geriebenen Parmesan unterrühren, bis er geschmolzen ist. Nochmals mit Salz und Pfeffer abschmecken.",
        "parallel": null,
        "timer": 120
      },
      {
        "header": "Portionieren & einfrieren",
        "body": "In 4 Portionen aufteilen, vollständig auskühlen lassen, dann in Gefrierdosen einfrieren.",
        "parallel": null,
        "timer": null
      },
      {
        "header": "Auftauen",
        "body": "Über Nacht im Kühlschrank auftauen, dann bei niedriger Hitze langsam erwärmen. Achtung: Sahnesaucen können beim Einfrieren/Auftauen leicht \"brechen\" (entmischen) — beim Erwärmen einen Schuss Sahne oder Milch unterrühren, dann wird die Sauce wieder cremig.",
        "parallel": null,
        "timer": null
      }
    ]
  },
  {
    "id": "pangasius-suesskartoffel-batch-x-3",
    "title": "Pangasius + Süßkartoffel",
    "category": "Hauptmahlzeit",
    "rating": 5,
    "prepTimeMin": 25,
    "kcalPortion": 420,
    "proteinPortion": 28,
    "batch": true,
    "portionen": 3,
    "einfrierbar": false,
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    "tags": [
      "protein",
      "prep",
      "quick"
    ],
    "baseIngredientName": "Süßkartoffel",
    "baseIngredientQty": 600.0,
    "unit": "g",
    "checklist": [
      {
        "name": "Pangasiusfilets (~450g)",
        "baseQty": 3.0,
        "unit": "x"
      },
      {
        "name": "Süßkartoffel (gewürfelt)",
        "baseQty": 600.0,
        "unit": "g"
      },
      {
        "name": "Tiefkühlgemüse",
        "baseQty": 300.0,
        "unit": "g"
      },
      {
        "name": "Olivenöl",
        "baseQty": 3.0,
        "unit": "EL"
      },
      {
        "name": "½ TL Za'atar",
        "baseQty": 1.0,
        "unit": "x"
      },
      {
        "name": "½ TL Paprika geräuchert",
        "baseQty": 1.0,
        "unit": "x"
      },
      {
        "name": "Salz",
        "baseQty": 1.0,
        "unit": "TL"
      },
      {
        "name": "Pfeffer",
        "baseQty": 0.5,
        "unit": "TL"
      },
      {
        "name": "Spritzer Zitrone (optional)",
        "baseQty": 1,
        "unit": "x"
      },
      {
        "name": "Optional Beilage: 3 × 80g Reis (roh) → unten im Dampfgarer mitkochen",
        "baseQty": 1,
        "unit": "x"
      }
    ],
    "steps": [
      {
        "header": "Süßkartoffel schälen, würfeln → unten in Dampfgarer (Reis wenn gewünscht dazu)",
        "body": "Süßkartoffel schälen, würfeln → unten in Dampfgarer (Reis wenn gewünscht dazu)",
        "parallel": null,
        "timer": null
      },
      {
        "header": "Pangasius drauf, Tiefkühlgemüse dazu",
        "body": "Pangasius drauf, Tiefkühlgemüse dazu",
        "parallel": null,
        "timer": null
      },
      {
        "header": "22 min dämpfen",
        "body": "22 min dämpfen",
        "parallel": "⚡ Parallel: Optional Beilage: 3 × 80g Reis (roh) → unten im Dampfgarer mitkochen",
        "timer": 1320
      },
      {
        "header": "Öl drüber, würzen, fertig",
        "body": "Öl drüber, würzen, fertig\n---",
        "parallel": null,
        "timer": null
      }
    ]
  },
  {
    "id": "sesamhuhn-an-karottenpueree-batch-x-3",
    "title": "Sesamhuhn an Karottenpüree",
    "category": "Hauptmahlzeit",
    "rating": 4,
    "prepTimeMin": 30,
    "kcalPortion": 820,
    "proteinPortion": 56,
    "batch": true,
    "portionen": 3,
    "einfrierbar": false,
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    "tags": [
      "protein",
      "prep",
      "quick"
    ],
    "baseIngredientName": "Hähnchenbrustfilet",
    "baseIngredientQty": 500.0,
    "unit": "g",
    "checklist": [
      {
        "name": "*Sesamhuhn**",
        "baseQty": 1,
        "unit": "x"
      },
      {
        "name": "Hähnchenbrustfilet",
        "baseQty": 500.0,
        "unit": "g"
      },
      {
        "name": "Eier (verquirlt)",
        "baseQty": 2.0,
        "unit": "x"
      },
      {
        "name": "Milch",
        "baseQty": 2.0,
        "unit": "EL"
      },
      {
        "name": "Mehl",
        "baseQty": 70.0,
        "unit": "g"
      },
      {
        "name": "Sesam",
        "baseQty": 6.0,
        "unit": "EL"
      },
      {
        "name": "Öl (zum Braten)",
        "baseQty": 6.0,
        "unit": "EL"
      },
      {
        "name": "Salz & Pfeffer",
        "baseQty": 1,
        "unit": "x"
      },
      {
        "name": "*Karottenpüree**",
        "baseQty": 1,
        "unit": "x"
      },
      {
        "name": "Karotten",
        "baseQty": 500.0,
        "unit": "g"
      },
      {
        "name": "iter Gemüsebrühe (aus der [[Selbstgemachte Gemüsebrüh-Paste (15 Lit. Brühe)|Brüh-Paste]])",
        "baseQty": 1.0,
        "unit": "L"
      },
      {
        "name": "½ EL Butter",
        "baseQty": 1.0,
        "unit": "x"
      },
      {
        "name": "Zucker",
        "baseQty": 1.0,
        "unit": "TL"
      },
      {
        "name": "Sahne",
        "baseQty": 2.0,
        "unit": "EL"
      },
      {
        "name": "Salz & Pfeffer",
        "baseQty": 1,
        "unit": "x"
      },
      {
        "name": "Cayennepfeffer",
        "baseQty": 1.0,
        "unit": "Prise"
      },
      {
        "name": "Muskat",
        "baseQty": 1.0,
        "unit": "Prise"
      }
    ],
    "steps": [
      {
        "header": "Fleisch schneiden (5 Min)",
        "body": "Hähnchenbrust trockentupfen und in Streifen schneiden (ca. 1 cm breit — dünner wird die Panade trocken, dicker gart der Kern nicht durch).",
        "parallel": null,
        "timer": 300
      },
      {
        "header": "Panierstraße aufbauen (3 Min)",
        "body": "Eier verquirlen, mit der Milch verrühren, mit Salz und Pfeffer würzen. In einem zweiten Teller Mehl und Sesam vermischen.",
        "parallel": null,
        "timer": 180
      },
      {
        "header": "Panieren",
        "body": "Fleischstreifen erst durch das Ei ziehen, gut abtropfen lassen, dann in der Mehl-Sesam-Mischung wälzen und andrücken.",
        "parallel": null,
        "timer": null
      },
      {
        "header": "Braten (6–8 Min)",
        "body": "Öl in der Pfanne stark erhitzen. Streifen **portionsweise** knusprig braten — zu viel auf einmal und der Sesam dünstet statt zu rösten. Auf Küchenpapier abtropfen lassen, im Ofen bei 80 °C warm stellen.\n**Karottenpüree** (läuft parallel)",
        "parallel": null,
        "timer": 360
      },
      {
        "header": "Kochen (12 Min)",
        "body": "Karotten schälen, in Scheiben schneiden, in der Gemüsebrühe weich kochen.",
        "parallel": null,
        "timer": 720
      },
      {
        "header": "Stampfen & abschmecken (5 Min)",
        "body": "Abtropfen lassen (Brühe auffangen — falls das Püree zu fest wird, löffelweise zurückgeben), fein stampfen. Butter, Zucker und Sahne unterrühren. Mit Salz, Pfeffer, Cayennepfeffer und Muskat abschmecken.\n---",
        "parallel": null,
        "timer": 300
      }
    ]
  },
  {
    "id": "pizzateig-wie-beim-italiener-batch-x-4",
    "title": "Pizzateig wie beim Italiener",
    "category": "Basics",
    "rating": 5,
    "prepTimeMin": 30,
    "kcalPortion": 446,
    "proteinPortion": 13,
    "batch": true,
    "portionen": 4,
    "einfrierbar": true,
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    "tags": [
      "prep",
      "quick"
    ],
    "baseIngredientName": "Weizenmehl",
    "baseIngredientQty": 500.0,
    "unit": "g",
    "checklist": [
      {
        "name": "Weizenmehl (Type 405 oder Pizza-Mehl Type 00)",
        "baseQty": 500.0,
        "unit": "g"
      },
      {
        "name": "lauwarmes Wasser (30–35 °C)",
        "baseQty": 300.0,
        "unit": "ml"
      },
      {
        "name": "Salz",
        "baseQty": 2.0,
        "unit": "TL"
      },
      {
        "name": "Frischhefe (oder 1,5–2g Trockenhefe)",
        "baseQty": 5.0,
        "unit": "g"
      }
    ],
    "steps": [
      {
        "header": "Vorbereitung",
        "body": "Mehl mit dem Salz in eine Rührschüssel/Küchenmaschine sieben. Die Frischhefe im lauwarmen Wasser auflösen (Trockenhefe kann direkt unter das Mehl gemischt werden).",
        "parallel": null,
        "timer": null
      },
      {
        "header": "Kneten (20 Min)",
        "body": "Das Hefewasser zum Mehl geben und den Teig **volle 20 Minuten** gründlich verkneten (am besten mit Küchenmaschine oder Knethaken). Das lange Kneten ist entscheidend, um das Glutengerüst optimal zu entwickeln, damit der Teig elastisch wird und sich dünn ausziehen lässt.",
        "parallel": null,
        "timer": 1200
      },
      {
        "header": "Erste Ruhephase (2 Std)",
        "body": "Schüssel mit einem feuchten Tuch abdecken und bei Raumtemperatur **2 Stunden** ruhen lassen.",
        "parallel": null,
        "timer": 7200
      },
      {
        "header": "Portionieren & Haupt-Gehzeit (6 Std)",
        "body": "Den Teig auf einer leicht bemehlten Arbeitsfläche in 4 gleich große Stücke (à ca. 200 g) teilen. Jedes Stück zu einer glatten Kugel schleifen (Oberflächenspannung aufbauen). Abgedeckt weitere **6 Stunden** bei Raumtemperatur (oder über Nacht im Kühlschrank) gehen lassen.",
        "parallel": null,
        "timer": 21600
      },
      {
        "header": "Formen & Belegen",
        "body": "Ofen auf maximale Temperatur vorheizen (250–270 °C, ideal mit Pizzastein). Teigkugel nicht mit dem Nudelholz plattwalzen, sondern vorsichtig von innen nach außen mit den Fingern zu einem flachen Fladen dehnen (Rand dick lassen). Nach Wunsch spärlich belegen.",
        "parallel": null,
        "timer": null
      },
      {
        "header": "Backen",
        "body": "Im heiß vorgeheizten Ofen auf unterster/mittlerer Schiene ca. 7–12 Minuten knusprig backen.\n---",
        "parallel": null,
        "timer": 720
      }
    ]
  },
  {
    "id": "selbstgemachte-gemuesebrueh-paste-batch-x-50",
    "title": "Selbstgemachte Gemüsebrüh-Paste",
    "category": "Basics",
    "rating": 5,
    "prepTimeMin": 10,
    "kcalPortion": 5,
    "proteinPortion": 20,
    "batch": true,
    "portionen": 50,
    "einfrierbar": true,
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    "tags": [
      "prep",
      "quick"
    ],
    "baseIngredientName": "Suppengrün",
    "baseIngredientQty": 500.0,
    "unit": "g",
    "checklist": [
      {
        "name": "Suppengrün (Karotten, Sellerie, Lauch, Petersilie)",
        "baseQty": 500.0,
        "unit": "g"
      },
      {
        "name": "Salz (feines Speisesalz oder Meersalz)",
        "baseQty": 100.0,
        "unit": "g"
      },
      {
        "name": "*Optional:* 1 Knoblauchzehe, ½ TL Pfefferkörner oder ½ TL Kurkuma (für schöne gelbe Farbe)",
        "baseQty": 1,
        "unit": "x"
      },
      {
        "name": "*Ertrag:** ca. 600g fertige Paste (ca. 50–60 Teelöffel / 50–60 Portionen à 250 ml Brühe).",
        "baseQty": 1,
        "unit": "x"
      },
      {
        "name": "*Nährwerte (pro Portion Brühe / 1 TL Paste):** ~5 kcal · ~0,2g Protein · ~1g KH · ~0g Fett",
        "baseQty": 1,
        "unit": "x"
      },
      {
        "name": "--",
        "baseQty": 1,
        "unit": "x"
      }
    ],
    "steps": [
      {
        "header": "Vorbereiten (5 Min)",
        "body": "Suppengrün gründlich waschen. Karotten und Sellerie schälen und grob würfeln. Lauch in grobe Stücke schneiden. Petersilie grob hacken.",
        "parallel": null,
        "timer": 300
      },
      {
        "header": "Pürieren (3 Min)",
        "body": "Das geschnittene Gemüse zusammen mit den 100 g Salz in einen leistungsstarken Mixer oder eine Küchenmaschine geben. Für 60 bis 120 Sekunden auf höchster Stufe pürieren, bis eine feine, gleichmäßige Paste entsteht (zwischendurch mit dem Spachtel von den Rändern nach unten schieben).",
        "parallel": null,
        "timer": 180
      },
      {
        "header": "Abfüllen",
        "body": "Die Paste in saubere, vorzugsweise heiß ausgekochte Schraubgläser (z. B. alte Marmeladengläser) füllen und fest verschließen.\n---",
        "parallel": null,
        "timer": null
      }
    ]
  },
  {
    "id": "topfen-creme",
    "title": "Topfen-Creme",
    "category": "Basics",
    "rating": 5,
    "prepTimeMin": 2,
    "kcalPortion": 445,
    "proteinPortion": 29,
    "batch": false,
    "portionen": 1,
    "einfrierbar": false,
    "image": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80",
    "tags": [
      "protein",
      "quick"
    ],
    "baseIngredientName": "Topfen",
    "baseIngredientQty": 250.0,
    "unit": "g",
    "checklist": [
      {
        "name": "Topfen",
        "baseQty": 250.0,
        "unit": "g"
      },
      {
        "name": "Honig oder Sirup",
        "baseQty": 1.0,
        "unit": "EL"
      },
      {
        "name": "Apfel (gewürfelt)",
        "baseQty": 0.5,
        "unit": "x"
      },
      {
        "name": "Leinsamen",
        "baseQty": 1.0,
        "unit": "EL"
      },
      {
        "name": "Leinöl (oder Olivenöl)",
        "baseQty": 1.0,
        "unit": "EL"
      },
      {
        "name": "*Grob:** ~445 kcal · ~29g Protein",
        "baseQty": 1,
        "unit": "x"
      },
      {
        "name": "--",
        "baseQty": 1,
        "unit": "x"
      }
    ],
    "steps": [
      {
        "header": "Topfen in Schüssel",
        "body": "Topfen in Schüssel",
        "parallel": null,
        "timer": null
      },
      {
        "header": "Öl + Honig/Sirup einrühren",
        "body": "Öl + Honig/Sirup einrühren",
        "parallel": null,
        "timer": null
      },
      {
        "header": "Apfel drauf, Leinsamen drüber",
        "body": "Apfel drauf, Leinsamen drüber",
        "parallel": null,
        "timer": null
      },
      {
        "header": "Fertig",
        "body": "Fertig\n---",
        "parallel": null,
        "timer": null
      }
    ]
  }
];

export const initialLeftovers = [
  {
    "id": "rest-1",
    "title": "Omas Kartoffelsuppe",
    "qty": 2,
    "unit": "Portionen",
    "addedDate": "2026-07-24",
    "daysRemaining": 2
  },
  {
    "id": "rest-2",
    "title": "Hähnchen süß-sauer",
    "qty": 1,
    "unit": "Portion",
    "addedDate": "2026-07-25",
    "daysRemaining": 3
  }
];

export const initialFreezerItems = [
  {
    "id": "freezer-1",
    "title": "Hühnerfrikassee Batch",
    "qty": 3,
    "unit": "Dosen",
    "frozenDate": "2026-07-20",
    "mhd": "2026-10-20"
  },
  {
    "id": "freezer-2",
    "title": "Linsen-Bolognese",
    "qty": 2,
    "unit": "Dosen",
    "frozenDate": "2026-07-21",
    "mhd": "2026-10-21"
  },
  {
    "id": "freezer-3",
    "title": "Muffins Hafer (Batch x 4)",
    "qty": 4,
    "unit": "Stück",
    "frozenDate": "2026-07-22",
    "mhd": "2026-09-22"
  }
];
